apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment-user22
  namespace: ns-user-22
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: iad.ocir.io/ocuocictrng31/iad-dop-lab03-ocir-1/oci_webapp_arm_user22:${BUILDRUN_HASH}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ocir-secret-user-22
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service-user22
  namespace: ns-user-22
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: helloworld
